// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuebH6yXVsN7TZATuy8cQ5ZT-ds5OrKC8',
    appId: '1:523578905375:web:bbd4b96d58b6238996962a',
    messagingSenderId: '523578905375',
    projectId: 'quranirab-form',
    authDomain: 'quranirab-form.firebaseapp.com',
    storageBucket: 'quranirab-form.appspot.com',
    measurementId: 'G-GN1XB5X69G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuIuH_0Ovvk0eU-ll-tbRPKpi3EwEAd-k',
    appId: '1:523578905375:android:59a86ef0bd41e0ed96962a',
    messagingSenderId: '523578905375',
    projectId: 'quranirab-form',
    storageBucket: 'quranirab-form.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb56fhjs_Z45CUrDxvzqQgxvPUJheSIUo',
    appId: '1:523578905375:ios:1d77b32c929cbe8b96962a',
    messagingSenderId: '523578905375',
    projectId: 'quranirab-form',
    storageBucket: 'quranirab-form.appspot.com',
    iosBundleId: 'com.example.formProjectOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb56fhjs_Z45CUrDxvzqQgxvPUJheSIUo',
    appId: '1:523578905375:ios:2b179448f44d717d96962a',
    messagingSenderId: '523578905375',
    projectId: 'quranirab-form',
    storageBucket: 'quranirab-form.appspot.com',
    iosBundleId: 'com.example.formProjectOne.RunnerTests',
  );
}
